version: "3.8"

services:  
  insta-auth: 
    container_name: insta-auth
    build: ./instagram-auth
    depends_on:
      -   mongodb 
    volumes:
      - .:/usr/app2/v
    networks:
      - insta-server

  insta-post: 
    container_name: insta-post
    build: ./instagram-posts
    depends_on:
      -   mongodb    
    volumes:
      - .:/usr/app/v
    networks:
      - insta-server

  mongodb:
    container_name: mongodb
    image: mongo          
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    volumes:
       - /mongodb/database:/data/db
        
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - insta-server
    restart: unless-stopped
  
  
 
networks:
  insta-server:
    driver: bridge

volumes:
    mongodb: